describe('Registration for DemoQA site', function () {
    it('Registration with valid input', function () {
        cy.visit('https://demoqa.com/automation-practice-form')
        cy.get('#firstName').type('Jo').should('have.value', 'Jo')
        cy.get('#lastName').type('Jo').should('have.value', 'Jo')
        cy.get('#userEmail').type('jojo@test.id').should('have.value', 'jojo@test.id')
        cy.get('input[value="Male"]').check({force: true}).should('be.checked')
        cy.get('#userNumber').type('0812345678').should('have.value', '0812345678')
        cy.get('input[value="1"]').check({force: true}).should('be.checked')
        cy.get('input[value="2"]').check({force: true}).should('be.checked')
        cy.get('input[value="3"]').check({force: true}).should('be.checked')
        cy.get('#dateOfBirthInput').invoke('val', '23 May 1999').should('have.value', '23 May 1999')
        cy.get('#subjectsContainer').type('Math{enter}')
        cy.get('#uploadPicture').attachFile('fp.jpg')
        cy.get('#currentAddress').type('rumah')
        cy.get('#city').find('input').should('be.disabled')
        cy.get('#state').type('NCR{enter}')
        cy.get('#city').type('Delhi{enter}')
        cy.get('#submit').click()
        cy.get('#closeLargeModal').click({force: true})
    })
})